### ISSUE TITLE
如果有server.servlet.context-path的话会导致自身实例连接订阅其他实例失败且PathMessage全部变成死信消息导致接收不到

### ISSUE THREAD

**Issue by anganing** [Linyuzai/concept#40]
依赖名称：
concept-websocket-loadbalance-spring-boot-starter
依赖版本：
1.X和2.x都有这个问题
问题描述：
一、有server.servlet.context-path的话会导致自身实例连接订阅其他实例失败这个比较好解决在1.x版本可以通过在项目下重写这个类
com.github.linyuzai.connection.loadbalance.core.subscribe.AbstractConnectionSubscriber
![image](https://github.com/Linyuzai/concept/assets/63218247/81baad3e-50b8-4b64-a723-e99d51b9bd80)
2.x的版本我没看到在哪里可以重写这个订阅地址
二、有server.servlet.context-path的话会导致致命问题：PathMessage全部变成死信消息导致接收不到
比如我要根据用户userId=729来做路径发送消息（这里是想不管同一用户有多少个client实例都要接收到消息）
异常堆栈：
发送消息后websocket client 没有接收到消息：
![image](https://github.com/Linyuzai/concept/assets/63218247/7d3db520-5100-43a6-8b2c-d6a0adcb638a)
debug进去查看原因：
![image](https://github.com/Linyuzai/concept/assets/63218247/ca9d5408-0f8c-4586-a1b2-79b279b848f4)
当我去掉server.servlet.context-path测试正常：
![image](https://github.com/Linyuzai/concept/assets/63218247/363d6220-c996-432a-96bd-8ed2d85e4552)

代码示例：
appliaction.yml:
![image](https://github.com/Linyuzai/concept/assets/63218247/71d214d2-4f40-45f7-939a-50901543a6c8)
发送消息代码：
![image](https://github.com/Linyuzai/concept/assets/63218247/fe571ad7-250a-461c-93c7-2a3091084b07)

**Comment by Linyuzai** [comment]
之前没有考虑额外的前缀，这几天我看下，在配置文件里面加一个配置可以自定义应该就行了

**Comment by Linyuzai** [comment]
2.6.0的版本加了配置可以解决PathMessage匹配不到的问题，可以试一下

```yaml
concept:
  websocket:
    server:
      default-endpoint:
        path-selector:
          enabled: true
          prefix: /api/sys/concept-websocket #这里配置前缀
```
